# Generated by Django 2.0.5 on 2018-06-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenthumb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='humidity',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='sensors',
            name='light_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sensors',
            name='soil_moisture',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='sensors',
            name='unit_id',
            field=models.BigIntegerField(default=10101010101101),
        ),
    ]
