# Generated by Django 2.0.5 on 2018-06-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenthumb', '0002_auto_20180610_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='temp',
            field=models.IntegerField(default=20, max_length=50),
        ),
    ]
