# Generated by Django 2.0.5 on 2018-07-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenthumb', '0003_auto_20180610_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='temp',
            field=models.IntegerField(default=20),
        ),
    ]
