# Generated by Django 2.1 on 2018-08-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenthumb', '0004_auto_20180708_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='unit_id',
            field=models.CharField(default='10101010101101', max_length=200),
        ),
    ]
