# Generated by Django 2.1 on 2018-08-20 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greenthumb', '0005_auto_20180820_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensors',
            name='snapshot',
            field=models.ImageField(blank=True, upload_to='static/snapshots'),
        ),
    ]
