# Generated by Django 2.1 on 2018-08-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenthumb', '0009_auto_20180822_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='snapshot',
            field=models.ImageField(blank=True, upload_to='snapshots'),
        ),
    ]
