# Generated by Django 2.1 on 2018-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenthumb', '0010_auto_20180823_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='water_tank',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
