# Generated by Django 2.0.5 on 2018-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20180528_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default='STRING', max_length=40),
        ),
    ]
