# Generated by Django 2.0.5 on 2018-05-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_skill_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(default='STRING', max_length=40)),
                ('education_institution', models.CharField(default='STRING', max_length=40)),
                ('education_dates', models.CharField(default='STRING', max_length=15)),
                ('education_synopsis1', models.CharField(default='STRING', max_length=200)),
                ('education_synopsis2', models.CharField(default='STRING', max_length=200)),
                ('education_synopsis3', models.CharField(default='STRING', max_length=200)),
                ('education_synopsis4', models.CharField(default='STRING', max_length=200)),
                ('education_synopsis5', models.CharField(default='STRING', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='STRING', max_length=40)),
                ('project_url', models.FilePathField(default='PATH')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(default='STRING', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(default='STRING', max_length=40)),
                ('work_institution', models.CharField(default='STRING', max_length=40)),
                ('work_dates', models.CharField(default='STRING', max_length=15)),
                ('work_synopsis1', models.CharField(default='STRING', max_length=200)),
                ('work_synopsis2', models.CharField(default='STRING', max_length=200)),
                ('work_synopsis3', models.CharField(default='STRING', max_length=200)),
                ('work_synopsis4', models.CharField(default='STRING', max_length=200)),
                ('work_synopsis5', models.CharField(default='STRING', max_length=200)),
            ],
        ),
    ]
