# Generated by Django 2.0.5 on 2018-05-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_eduction_project_tool_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.FilePathField(),
        ),
    ]
