# Generated by Django 2.0.5 on 2018-05-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20180529_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(default='FILE_PATH', max_length=40),
        ),
    ]
