# Generated by Django 2.0.5 on 2018-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20180529_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_path',
            field=models.CharField(default='FILE_PATH', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(default='SITE_URL', max_length=100),
        ),
    ]
