# Generated by Django 2.0.5 on 2018-06-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20180529_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduction',
            name='education_synopsis1',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='eduction',
            name='education_synopsis2',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='eduction',
            name='education_synopsis3',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='eduction',
            name='education_synopsis4',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='eduction',
            name='education_synopsis5',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_synopsis1',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_synopsis2',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_synopsis3',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_synopsis4',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_synopsis5',
            field=models.CharField(blank=True, default='STRING', max_length=200),
        ),
    ]
