# Generated by Django 2.0.5 on 2018-06-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20180601_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduction',
            name='education_dates',
            field=models.CharField(default='STRING', max_length=40),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_dates',
            field=models.CharField(default='STRING', max_length=40),
        ),
    ]
